### ISSUE TITLE
老哥，会报毒。。。

### ISSUE THREAD

**Issue by ChenYun4164** [dogadmin/windodws-logs-analysis#4]
分析报告如下：
https://www.virustotal.com/gui/file/e1521a2cacddf30367e0098fac28c211e8fac5f972c890e8376fd35a68762af7
https://s.threatbook.com/report/file/e1521a2cacddf30367e0098fac28c211e8fac5f972c890e8376fd35a68762af7?sign=history&env=win7_sp1_enx86_office2013

**Comment by dogadmin** [comment]
看到了，如果觉得不放心可以放在虚拟机使用，实际写法因为调用了cmd去执行logp的进程，所以会报毒。因为命中了调用的进程。实际上程序没有任何外联行为。在更新前，你可以把日志导入到c://log之后进行断网本地分析也可以
